Corrigindo exemplos de dicionarios na documentacao da linguagem
eguatech/docs pull request #49
Opened 2021-10-28 22:29 UTC by asafedainez

Na página https://egua.tech/docs/egua/tipos_dados.html#dicionarios a descrição do tipo de dado Dicionário não está funcional. Abri essa issue #48 para corrigir o mesmo.

2022-01-09 21:13 UTC, lucaspompeun commented
Olá, @asafedainez. Tudo bem?
A demora a responder seu PR se deu devido a problemas com o deploy da documentação, este problema já foi resolvido e podemos fazer o merge, entretanto algumas alterações precisam ser feitas, como e exclusão do commmit dos arquivos presente na pasta `docs/.vuepress/dist/`.

2022-01-09 21:13 UTC, lucaspompeun requested changes
Remover os arquivos da pasta `docs/.vuepress/dist/`

2022-01-22 18:37 UTC, asafedainez commented
> Remover os arquivos da pasta `docs/.vuepress/dist/`

Como solicitado, foram removidos os aquivos presentes na pasta.

2022-01-23 15:25 UTC, lucaspompeun commented
@asafedainez ainda há um conflito com os arquivos package-lock.json e yarn.lock, eu não consigo resolver por aqui, por isso a sinalização

2022-04-25 20:07 UTC, closed without merging